improved test script, added piepline to README

diff --git a/test-vote-app b/test-vote-app
--- a/test-vote-app
+++ b/test-vote-app
@@ -4,9 +4,10 @@
 
 for i in {1..20}
 do
-   echo Casting vote nr. $i
+   echo -n "Casting vote nr. $i "
    RESP=$(curl -o /tmp/.tempfile -w "%{http_code}\n" -s -X POST $1/vote.html -d "vote=`expr $(($RANDOM % 10)) + 1`")
-   [ "$RESP" != "200" ] && echo HTTP return code: $RESP && cat /tmp/.tempfile && echo Aborting test script ... && exit 1
+   [[ $RESP =~ 2.. ]] && echo "$RESP" && continue
+   echo $RESP && echo "HTTP return code non 200" && cat /tmp/.tempfile && echo Aborting test script ... && exit 1
 done
 exit 0
 
